"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var veiculos_1 = require("./veiculos");
var Caminhao_1 = require("./Caminhao");
var Moto_1 = require("./Moto");
var meuVeiculo = new veiculos_1.Veiculo("azul", "Toyota", "Corolla");
console.log("Veículo - Cor:", meuVeiculo.cor);
console.log("Veículo - Fabricante:", meuVeiculo.fabricante);
console.log("Veículo - Modelo:", meuVeiculo.modelo);
meuVeiculo.acelerar();
meuVeiculo.parar();
var meuCaminhao = new Caminhao_1.Caminhao("vermelho", "Volvo", "FH16", 10);
console.log("Caminhão - Cor:", meuCaminhao.cor);
console.log("Caminhão - Fabricante:", meuCaminhao.fabricante);
console.log("Caminhão - Modelo:", meuCaminhao.modelo);
console.log("Caminhão - Caçamba:", meuCaminhao.cacamba);
meuCaminhao.acelerar();
meuCaminhao.parar();
meuCaminhao.descarregar();
var minhaMoto = new Moto_1.Moto("preta", "Honda", "CBR600RR");
console.log("Moto - Cor:", minhaMoto.cor);
console.log("Moto - Fabricante:", minhaMoto.fabricante);
console.log("Moto - Modelo:", minhaMoto.modelo);
minhaMoto.acelerar();
minhaMoto.parar();
minhaMoto.empinar();
